### ISSUE TITLE
ArrayOfDoubles P-Value Ratio Metric

### ISSUE THREAD

**Issue by joshwalters** [DataSketches/sketches-pig#47]
The `ArrayOfDoublesSketchesToPValueEstimates` UDF generates p-values for given metrics. However, we have need of p-values for ratio metrics. For example, the click-through rate (CTR) is computed as `clicks / impressions`. Impressions would be a metric, and clicks would be a metric. We would need to compute the p-value for that ratio, and be able to express it in terms of a UDF.

I think a UDF that takes the following parameters: 

```RATIO_PVALUE(sketch_A, sketch_B, numerator_index, denominator_index)```

and returns a map:

```{'pvalue': X, 'delta': Y}```

The math required for ratio p-value computation is different from regular p-value computation.

**Comment by AlexanderSaydakov** [comment]
This seems to be a very custom function. Closing this old issue we are not likely to address.
